# Generated by Django 4.2.16 on 2024-11-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_featured_featuredproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
