# Generated by Django 4.2.16 on 2024-11-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_is_featured_delete_featuredproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='0-default,1-Featured'),
        ),
    ]
