# Generated by Django 5.1.3 on 2024-11-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_customuser_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
